INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Path of the Berserker', 1);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Path of the Totem Warrior', 1);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Path of the Battlerager', 1);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Path of the Ancestral Guardian', 1);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Path of the Storm Herald', 1);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Path of the Zealot', 1);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('College of Lore', 2);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('College of Valor', 2);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('College of Glamour', 2);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('College of Swords', 2);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('College of Whispers', 2);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('College of Eloquence', 2);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Knowledge Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Life Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Light Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Nature Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Tempest Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Trickery Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('War Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Arcana Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Forge Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Grave Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Order Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Death Domain', 3);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Circle of the Land', 4);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Circle of the Moon', 4);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Circle of Dreams', 4);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Circle of the Shepherd', 4);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Circle of Spores', 4);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Champion', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Battle Master', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Eldritch Knight', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Purple Dragon Knight', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Arcane Archer', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Cavalier', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Samurai', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Echo Knight', 5);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of the Open Hand', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of Shadow', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of the Four Elements', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of the Long Death', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of the Sun Soul', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of the Drunken Master', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Way of the Kensei', 6);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of Devotion', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of the Ancients', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of Vengeance', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of the Crown', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of Conquest', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of Redemption', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oath of Glory', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Oathbreaker', 7);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Hunter', 8);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Beast Master', 8);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Gloom Stalker', 8);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Horizon Walker', 8);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Monster Slayer', 8);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Assassin', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Thief', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Arcane Trickster', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Mastermind', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Swashbuckler', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Inquisitive', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Scout', 9);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Draconic Bloodline', 10);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Wild Magic', 10);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Storm Sorcerer', 10);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Divine Soul', 10);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Shadow Magic', 10);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('The Archfey', 11);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('The Fiend', 11);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('The Great Old One', 11);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('The Undying', 11);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('The Celestial', 11);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('The Hexblade', 11);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Abjuration', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Conjuration', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Divination', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Enchantment', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Evocation', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Illusion', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Necromancy', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('School of Transmutation', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Bladesinging', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('War Magic', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Chronurgy Magic', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Graviturgy Magic', 12);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Alchemist', 13);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Artillerist', 13);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Battle Smith', 13);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Order of the Ghostslayer', 14);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Order of the Lycan', 14);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Order of the Profane Soul', 14);
INSERT INTO dbo.SubClass(SubClassName, ClassId) VALUES('Order of the Mutant', 14);

